apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: webinarselfservice
  title: Python Backend Self Service
  description: An template to provide self service deployment/governance to developers
  tags:
    - python
    - harness
spec:
  owner: nikolaos.papageorgiou@harness.io
  type: service
  parameters:
    - title: Application Details
      required:
        - name
      properties:
        name:
          title: Name of your Banking Service - Repository
          type: string
          description: Unique name of the service
      properties:
        provider:
          title: Choose a cloud provider for Deployment
          type: string
          enum: ['GCP', 'AWS', "AZURE"]
          default: GCP
        db:
          title: Choose a Database Type for the Service
          type: string
          enum: ['None', 'MySQL', 'Postgres', 'MongoDB']
          default: None
        owner:
          title: Choose an Owner for the Service
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
  steps:
    # Call Harness Pipelines to create the service infra and other things
    - id: trigger
      name: Creating Your Infra for the Service
      action: trigger:harness-custom-pipeline
      input:
        url: 'https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/module/cd/orgs/default/projects/Onboarding_Demo/pipelines/Onboard_new_App/triggers/?storeType=INLINE'
        inputset:
          provider: ${{ parameters.provider }}
          db: ${{ parameters.db }}
          name: ${{ parameters.name }}
